package dev.ajthom.covid

class StateNames {
    fun getName(abbreviation: String): String {
        return stateNameMap[abbreviation] ?: abbreviation
    }

    val stateNameMap = mapOf("MN" to "Minnesota",
        "AK" to "Alaska",
        "AL" to "Alabama",
        "AR" to "Arkansas",
        "AS" to "American Samoa",
        "AZ" to "Arizona",
        "CA" to "California",
        "CO" to "Colorado",
        "CT" to "Connecticut",
        "DC" to "District of Columbia",
        "DE" to "Delaware",
        "FL" to "Florida",
        "GA" to "Georgia",
        "GU" to "Guam",
        "HI" to "Hawaii",
        "IA" to "Iowa",
        "ID" to "Idaho",
        "IL" to "Illinois",
        "IN" to "Indiana",
        "KS" to "Kansas",
        "KY" to "Kentucky",
        "LA" to "Louisiana",
        "MA" to "Massachusetts",
        "MD" to "Maryland",
        "ME" to "Maine",
        "MI" to "Michigan",
        "MO" to "Missouri",
        "MP" to "Northern Mariana Islands",
        "MS" to "Mississippi",
        "MT" to "Montana",
        "NC" to "North Carolina",
        "ND" to "North Dakota",
        "NE" to "Nebraska",
        "NH" to "New Hampshire",
        "NJ" to "New Jersey",
        "NM" to "New Mexico",
        "NV" to "Nevada",
        "NY" to "New York",
        "OH" to "Ohio",
        "OK" to "Oklahoma",
        "OR" to "Oregon",
        "PA" to "Pennsylvania",
        "PR" to "Puerto Rico",
        "RI" to "Rhode Island",
        "SC" to "South Carolina",
        "SD" to "South Dakota",
        "TN" to "Tennessee",
        "TX" to "Texas",
        "UT" to "Utah",
        "VA" to "Virginia",
        "VI" to "Virgin Islands",
        "VT" to "Vermont",
        "WA" to "Washington",
        "WI" to "Wisconsin",
        "WV" to "West Virginia",
        "WY" to "Wyoming"
    ).doFreeze()
}
